pm disable-user --user 0 com.android.chrome
pm disable-user --user 0 com.android.dreams.basic
pm disable-user --user 0 com.android.dreams.phototable
pm disable-user --user 0 com.android.egg
pm disable-user --user 0 com.android.hotwordenrollment.okgoogle
pm disable-user --user 0 com.android.hotwordenrollment.xgoogle
pm disable-user --user 0 com.android.internal.systemui.onehanded.gestural
pm disable-user --user 0 com.android.wallpaper.livepicker
pm disable-user --user 0 com.facebook.appmanager
pm disable-user --user 0 com.facebook.services
pm disable-user --user 0 com.facebook.system
pm disable-user --user 0 com.google.android.adservices.api
pm disable-user --user 0 com.google.android.apps.accessibility.voiceaccess
pm disable-user --user 0 com.google.android.apps.docs.editors.sheets
pm disable-user --user 0 com.google.android.apps.messaging
pm disable-user --user 0 com.google.android.apps.restore
pm disable-user --user 0 com.google.android.apps.setupwizard.searchselector
pm disable-user --user 0 com.google.android.as
pm disable-user --user 0 com.google.android.googlequicksearchbox
pm disable-user --user 0 com.google.android.gms.location.history
pm disable-user --user 0 com.google.android.gms.supervision
pm disable-user --user 0 com.google.android.healthconnect.controller
pm disable-user --user 0 com.google.android.safetycenter.resources
pm disable-user --user 0 com.google.android.youtube
pm disable-user --user 0 com.klim.dbdesigner
pm disable-user --user 0 com.microsoft.appmanager
pm disable-user --user 0 com.microsoft.office.word
pm disable-user --user 0 com.microsoft.skydrive
pm disable-user --user 0 com.redpi.apps.accelerometercalibrationfree
pm disable-user --user 0 com.samsung.accessibility
pm disable-user --user 0 com.samsung.aimodelprovider.reflectionremovalmodels
pm disable-user --user 0 com.samsung.aimodelprovider.shadowremovalmodels
pm disable-user --user 0 com.samsung.aimodelprovider.smartaiengine
pm disable-user --user 0 com.samsung.android.app.camera.sticker.facearavatar.preload
pm disable-user --user 0 com.samsung.android.app.cocktailbarservice
pm disable-user --user 0 com.samsung.android.app.omcagent
pm disable-user --user 0 com.samsung.android.app.routines
pm disable-user --user 0 com.samsung.android.app.settings.bixby
pm disable-user --user 0 com.samsung.android.app.sharelive
pm disable-user --user 0 com.samsung.android.app.spage
pm disable-user --user 0 com.samsung.android.ardrawing
pm disable-user --user 0 com.samsung.android.aremoji
pm disable-user --user 0 com.samsung.android.aremojieditor
pm disable-user --user 0 com.samsung.android.authfw
pm disable-user --user 0 com.samsung.android.beaconmanager
pm disable-user --user 0 com.samsung.android.bbc.bbcagent
pm disable-user --user 0 com.samsung.android.bixby.agent
pm disable-user --user 0 com.samsung.android.bixby.agent.dummy
pm disable-user --user 0 com.samsung.android.bixby.service
pm disable-user --user 0 com.samsung.android.bixby.vision.framework
pm disable-user --user 0 com.samsung.android.bixby.wakeup
pm disable-user --user 0 com.samsung.android.forest
pm disable-user --user 0 com.samsung.android.game.gamehome
pm disable-user --user 0 com.samsung.android.game.gametools
pm disable-user --user 0 com.samsung.android.game.gos
pm disable-user --user 0 com.samsung.android.game.home
pm disable-user --user 0 com.samsung.android.gpuwatchapp
pm disable-user --user 0 com.samsung.android.gru
pm disable-user --user 0 com.samsung.android.honeyboard
pm disable-user --user 0 com.samsung.android.inputmethod
pm disable-user --user 0 com.samsung.android.inputmethod.korean
pm disable-user --user 0 com.samsung.android.inputmethod.pinyin
pm disable-user --user 0 com.samsung.android.kgclient
pm disable-user --user 0 com.samsung.android.kidsinstaller
pm disable-user --user 0 com.samsung.android.knox.zt.framework
pm disable-user --user 0 com.samsung.android.mdx
pm disable-user --user 0 com.samsung.android.mdx.kit
pm disable-user --user 0 com.samsung.android.mapsagent
pm disable-user --user 0 com.samsung.android.mdx.quickboard
pm disable-user --user 0 com.samsung.android.mdx.settings
pm disable-user --user 0 com.samsung.android.mobileservice
pm disable-user --user 0 com.samsung.android.net.wifi.wifiguider
pm disable-user --user 0 com.samsung.android.peoplestripe
pm disable-user --user 0 com.samsung.android.peoplestripe.service
pm disable-user --user 0 com.samsung.android.peripheral.framework
pm disable-user --user 0 com.samsung.android.personalization
pm disable-user --user 0 com.samsung.android.photoremasterservice
pm disable-user --user 0 com.samsung.android.privateshare
pm disable-user --user 0 com.samsung.android.rampart
pm disable-user --user 0 com.samsung.android.rubin.app
pm disable-user --user 0 com.samsung.android.samsungpass
pm disable-user --user 0 com.samsung.android.samsungpassautofill
pm disable-user --user 0 com.samsung.android.scloud
pm disable-user --user 0 com.samsung.android.scpm
pm disable-user --user 0 com.samsung.android.service.livedrawing
pm disable-user --user 0 com.samsung.android.service.peoplestripe
pm disable-user --user 0 com.samsung.android.sharelive
pm disable-user --user 0 com.samsung.android.singletake.service
pm disable-user --user 0 com.samsung.android.sm.devicesecurity
pm disable-user --user 0 com.samsung.android.smartface
pm disable-user --user 0 com.samsung.android.spayfw
pm disable-user --user 0 com.samsung.android.stickercenter
pm disable-user --user 0 com.samsung.android.storyservice
pm disable-user --user 0 com.samsung.android.svoiceime
pm disable-user --user 0 com.samsung.android.themecenter
pm disable-user --user 0 com.samsung.android.themestore
pm disable-user --user 0 com.samsung.android.visionintelligence
pm disable-user --user 0 com.samsung.android.vtcamerasettings
pm disable-user --user 0 com.samsung.android.wallpaper.res.earth
pm disable-user --user 0 com.samsung.cmfa.AuthTouch
pm disable-user --user 0 com.samsung.safetyinformation
pm disable-user --user 0 com.samsung.smartswitchassistant
pm disable-user --user 0 com.sec.android.app.billing
pm disable-user --user 0 com.sec.android.app.dexonpc
pm disable-user --user 0 com.sec.android.app.desktoplauncher
pm disable-user --user 0 com.sec.android.app.personalization
pm disable-user --user 0 com.sec.android.app.sbrowser
pm disable-user --user 0 com.sec.android.autodoodle.service
pm disable-user --user 0 com.sec.android.daemonapp
pm disable-user --user 0 com.sec.android.dexsystemui
pm disable-user --user 0 com.sec.android.easyMover
pm disable-user --user 0 com.sec.android.easyMover.Agent
pm disable-user --user 0 com.sec.android.easyonehand
pm disable-user --user 0 com.sec.android.hearingadjust
pm disable-user --user 0 com.touchtype.swiftkey
pm disable-user --user 0 de.axelspringer.yana.zeropage
pm disable-user --user 0 org.toshi
pm disable-user --user 0 redpi.apps.accelerometercalibrationfree
# New
pm disable-user --user 0 com.samsung.android.app.watchmanagerstub
pm disable-user --user 0 com.android.managedprovisioning
pm disable-user --user 0 com.sec.android.app.quicktool
pm disable-user --user 0 com.samsung.android.app.taskedge
pm disable-user --user 0 com.samsung.android.svcagent
pm disable-user --user 0 android.autoinstalls.config.samsung
pm disable-user --user 0 com.android.bluetoothmidiservice
pm disable-user --user 0 com.android.providers.partnerbookmarks
pm disable-user --user 0 com.android.traceur
pm disable-user --user 0 com.google.android.feedback
pm disable-user --user 0 com.google.android.onetimeinitializer
pm disable-user --user 0 com.google.android.partnersetup
pm disable-user --user 0 com.google.android.printservice.recommendation
pm disable-user --user 0 com.samsung.android.aircommandmanager
pm disable-user --user 0 com.samsung.android.app.clipboardedge
pm disable-user --user 0 com.samsung.android.dqagent
pm disable-user --user 0 com.samsung.android.dynamiclock
pm disable-user --user 0 com.samsung.android.knox.analytics.uploader
pm disable-user --user 0 com.samsung.android.knox.attestation
pm disable-user --user 0 com.samsung.android.knox.containercore
pm disable-user --user 0 com.samsung.android.knox.pushmanager
pm disable-user --user 0 com.samsung.android.mdecservice
pm disable-user --user 0 com.samsung.android.mdm
pm disable-user --user 0 com.samsung.android.networkdiagnostic
pm disable-user --user 0 com.samsung.android.sdk.handwriting
pm disable-user --user 0 com.samsung.android.sdm.config
pm disable-user --user 0 com.samsung.android.shortcutbackupservice
pm disable-user --user 0 com.samsung.android.smartswitchassistant
pm disable-user --user 0 com.samsung.crane
pm disable-user --user 0 com.samsung.ipservice
pm disable-user --user 0 com.samsung.klmsagent
pm disable-user --user 0 com.samsung.knox.securefolder
pm disable-user --user 0 com.sec.android.app.apex
pm disable-user --user 0 com.sec.android.app.chromecustomizations
pm disable-user --user 0 com.sec.android.app.DataCreate
pm disable-user --user 0 com.sec.android.app.factorykeystring
pm disable-user --user 0 com.sec.android.app.hwmoduletest
pm disable-user --user 0 com.sec.android.app.magnifier
pm disable-user --user 0 com.sec.android.app.parser
pm disable-user --user 0 com.sec.android.app.SecSetupWizard
pm disable-user --user 0 com.sec.android.app.servicemodeapp
pm disable-user --user 0 com.sec.android.cover.ledcover
pm disable-user --user 0 com.sec.android.diagmonagent
pm disable-user --user 0 com.sec.android.RIIServiceModeApp
pm disable-user --user 0 com.sec.android.widgetapp.easymodecontactswidget
pm disable-user --user 0 com.sec.android.widgetapp.webmanual
pm disable-user --user 0 com.sec.app.RIIErrorNotifier
pm disable-user --user 0 com.sec.bcservice
pm disable-user --user 0 com.sec.enterprise.knox.cloudmdm.smdms
pm disable-user --user 0 com.sec.enterprise.mdm.services.simpin
pm disable-user --user 0 com.sec.epdgtestapp
pm disable-user --user 0 com.sec.factory.camera
pm disable-user --user 0 com.sec.imslogger
pm disable-user --user 0 com.sec.phone
pm disable-user --user 0 com.sec.spp.push
pm disable-user --user 0 com.sec.usbsettings
pm disable-user --user 0 com.sec.vsim.ericssonnsds.webapp
pm disable-user --user 0 com.sem.factoryapp
