# Run from adb shell
pm disable-user --user 0 com.samsung.android.game.gamehome
pm disable-user --user 0 com.samsung.android.game.gametools
pm disable-user --user 0 com.samsung.android.game.gos
pm disable-user --user 0 com.wsomacp
pm disable-user --user 0 com.samsung.android.aremoji
pm disable-user --user 0 com.samsung.android.da.daagent
pm disable-user --user 0 com.sec.android.mimage.avatarstickers
pm disable-user --user 0 com.samsung.android.samsungpassautofill
pm disable-user --user 0 com.samsung.android.authfw
pm disable-user --user 0 com.samsung.android.samsungpass
pm disable-user --user 0 com.samsung.android.spayfw
pm disable-user --user 0 com.samsung.android.bixby.wakeup
pm disable-user --user 0 com.samsung.android.app.spage
pm disable-user --user 0 com.samsung.android.app.routines
pm disable-user --user 0 com.samsung.android.bixby.service
pm disable-user --user 0 com.samsung.android.visionintelligence
pm disable-user --user 0 com.samsung.android.bixby.agent
pm disable-user --user 0 com.samsung.android.bixby.agent.dummy
pm disable-user --user 0 com.samsung.android.bixbyvision.framework
pm disable-user --user 0 com.samsung.systemui.bixby2
pm disable-user --user 0 com.samsung.android.themestore
pm disable-user --user 0 com.android.chrome
pm disable-user --user 0 com.samsung.android.themecenter
pm disable-user --user 0 com.google.android.googlequicksearchbox
pm disable-user --user 0 com.sec.android.easyonehand
pm disable-user --user 0 com.samsung.android.app.settings.bixby
pm disable-user --user 0 com.google.ar.core
pm disable-user --user 0 com.swiftkey.swiftkeyconfigurator
pm disable-user --user 0 com.facebook.appmanager
pm disable-user --user 0 com.facebook.services
pm disable-user --user 0 com.facebook.system
pm disable-user --user 0 com.samsung.android.scloud
pm disable-user --user 0 com.samsung.android.app.cocktailbarservice
pm disable-user --user 0 com.samsung.android.kidsinstaller
pm disable-user --user 0 com.samsung.android.privateshare
pm disable-user --user 0 com.samsung.android.svoiceime
pm disable-user --user 0 com.samsung.android.smartsuggestions
pm disable-user --user 0 com.samsung.android.app.camera.sticker.facearavatar.preload
pm disable-user --user 0 com.samsung.android.service.peoplestripe
pm disable-user --user 0 com.samsung.storyservice                                                                                                                                                         
pm disable-user --user 0 com.google.android.gms.location.history 
